package com.unicom.model;

import java.util.Date;

public class EventInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.id
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.event_id
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    private String eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.title
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.description
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.first_type
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    private String firstType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.start_time
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.tags
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.img_url
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.is_end
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    private Byte isEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.create_time
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.creator
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.update_time
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.updater
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    private String updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.id
     *
     * @return the value of event_info.id
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.id
     *
     * @param id the value for event_info.id
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.event_id
     *
     * @return the value of event_info.event_id
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.event_id
     *
     * @param eventId the value for event_info.event_id
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public void setEventId(String eventId) {
        this.eventId = eventId == null ? null : eventId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.title
     *
     * @return the value of event_info.title
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.title
     *
     * @param title the value for event_info.title
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.description
     *
     * @return the value of event_info.description
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.description
     *
     * @param description the value for event_info.description
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.first_type
     *
     * @return the value of event_info.first_type
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public String getFirstType() {
        return firstType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.first_type
     *
     * @param firstType the value for event_info.first_type
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public void setFirstType(String firstType) {
        this.firstType = firstType == null ? null : firstType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.start_time
     *
     * @return the value of event_info.start_time
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.start_time
     *
     * @param startTime the value for event_info.start_time
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.tags
     *
     * @return the value of event_info.tags
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.tags
     *
     * @param tags the value for event_info.tags
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.img_url
     *
     * @return the value of event_info.img_url
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.img_url
     *
     * @param imgUrl the value for event_info.img_url
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.is_end
     *
     * @return the value of event_info.is_end
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public Byte getIsEnd() {
        return isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.is_end
     *
     * @param isEnd the value for event_info.is_end
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public void setIsEnd(Byte isEnd) {
        this.isEnd = isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.create_time
     *
     * @return the value of event_info.create_time
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.create_time
     *
     * @param createTime the value for event_info.create_time
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.creator
     *
     * @return the value of event_info.creator
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.creator
     *
     * @param creator the value for event_info.creator
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.update_time
     *
     * @return the value of event_info.update_time
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.update_time
     *
     * @param updateTime the value for event_info.update_time
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.updater
     *
     * @return the value of event_info.updater
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.updater
     *
     * @param updater the value for event_info.updater
     *
     * @mbg.generated Fri Jul 26 16:50:46 CST 2019
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }
}